import type { Metadata } from "next";
import { Geist, Geist_Mono, Libre_Caslon_Text, Public_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const publicSans = Public_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Matches the "ilovelawyer" wordmark styling in ilovelawyer-app (navbar.tsx,
// unified-auth.tsx, global-header.tsx) — fontFamily: "'Libre Caslon Text', serif".
// Unlike that app, actually load it via next/font here rather than relying on the
// serif fallback.
const libreCaslonText = Libre_Caslon_Text({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-libre-caslon-text",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", publicSans.variable, libreCaslonText.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
